name: CheckStyle Release
on:
  release:
    types:
      - created

jobs:
  build:
    runs-on: ubuntu-latest
    steps: 
      - uses: actions/checkout@v2
      - name: Save Maven Settings
        run: |
          echo "<settings> <servers> <server> <id>github</id> <username>${GITHUB_USERNAME}</username> <password>${GITHUB_TOKEN}</password> </server> </servers> </settings>" > ~/.m2/settings.xml
      - name: Release startupheroes-checkstyle
        run: ./mvnw deploy
        
